"""initial migration

Revision ID: 640e03abb041
Revises: 
Create Date: 2026-06-14 13:37:32.039593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640e03abb041'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'Medium'"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'Medium'"))

    # ### end Alembic commands ###
